services:
  - type: web
    name: fetch-backend
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn server:app --workers 2 --timeout 300"
    envVars:
      - key: ACCESS_PASSWORD
        sync: false
